redirects:
  nats-tools/nas: ./legacy/nas/README.md
  nats-tools/nas/dir_store: ./legacy/nas/dir_store.md
  nats-tools/nas/inspecting_jwts: ./legacy/nas/inspecting_jwts.md
  nats-tools/nas/nas_conf: ./legacy/nas/nas_conf.md
  nats-tools/nas/notifications: ./legacy/nas/notifications.md
  developing-with-nats-streaming/acks: ./legacy/stan/developing-with-nats-streaming/acks.md
  developing-with-nats-streaming/connecting: ./legacy/stan/developing-with-nats-streaming/connecting.md
  developing-with-nats-streaming/durables: ./legacy/stan/developing-with-nats-streaming/durables.md
  developing-with-nats-streaming/protocol: ./legacy/stan/developing-with-nats-streaming/protocol.md
  developing-with-nats-streaming/publishing: ./legacy/stan/developing-with-nats-streaming/publishing.md
  developing-with-nats-streaming/queues: ./legacy/stan/developing-with-nats-streaming/queues.md
  developing-with-nats-streaming/receiving: ./legacy/stan/developing-with-nats-streaming/receiving.md
  developing-with-nats-streaming/streaming: ./legacy/stan/developing-with-nats-streaming/streaming.md
  nats-streaming-concepts/channels: ./legacy/stan/nats-streaming-concepts/channels/README.md
  nats-streaming-concepts/channels/message-log: ./legacy/stan/nats-streaming-concepts/channels/message-log.md
  nats-streaming-concepts/channels/subscriptions: ./legacy/stan/nats-streaming-concepts/channels/subscriptions/README.md
  nats-streaming-concepts/channels/subscriptions/durable: ./legacy/stan/nats-streaming-concepts/channels/subscriptions/durable.md
  nats-streaming-concepts/channels/subscriptions/queue-group: ./legacy/stan/nats-streaming-concepts/channels/subscriptions/queue-group.md
  nats-streaming-concepts/channels/subscriptions/redelivery: ./legacy/stan/nats-streaming-concepts/channels/subscriptions/redelivery.md
  nats-streaming-concepts/channels/subscriptions/regular: ./legacy/stan/nats-streaming-concepts/channels/subscriptions/regular.md
  nats-streaming-concepts/client-connections: ./legacy/stan/nats-streaming-concepts/client-connections.md
  nats-streaming-concepts/clustering: ./legacy/stan/nats-streaming-concepts/clustering/README.md
  nats-streaming-concepts/clustering/auto-configuration: ./legacy/stan/nats-streaming-concepts/clustering/auto-configuration.md
  nats-streaming-concepts/clustering/configuration: ./legacy/stan/nats-streaming-concepts/clustering/configuration.md
  nats-streaming-concepts/clustering/containers: ./legacy/stan/nats-streaming-concepts/clustering/containers.md
  nats-streaming-concepts/clustering/supported-stores: ./legacy/stan/nats-streaming-concepts/clustering/supported-stores.md
  nats-streaming-concepts/ft: ./legacy/stan/nats-streaming-concepts/ft/README.md
  nats-streaming-concepts/ft/active-server: ./legacy/stan/nats-streaming-concepts/ft/active-server.md
  nats-streaming-concepts/ft/failover: ./legacy/stan/nats-streaming-concepts/ft/failover.md
  nats-streaming-concepts/ft/shared-state: ./legacy/stan/nats-streaming-concepts/ft/shared-state.md
  nats-streaming-concepts/ft/standby-server: ./legacy/stan/nats-streaming-concepts/ft/standby-server.md
  nats-streaming-concepts/intro: ./legacy/stan/nats-streaming-concepts/intro.md
  nats-streaming-concepts/monitoring: ./legacy/stan/nats-streaming-concepts/monitoring/README.md
  nats-streaming-concepts/monitoring/endpoints: ./legacy/stan/nats-streaming-concepts/monitoring/endpoints.md
  nats-streaming-concepts/partitioning: ./legacy/stan/nats-streaming-concepts/partitioning.md
  nats-streaming-concepts/relation-to-nats: ./legacy/stan/nats-streaming-concepts/relation-to-nats.md
  nats-streaming-concepts/store-encryption: ./legacy/stan/nats-streaming-concepts/store-encryption.md
  nats-streaming-concepts/store-interface: ./legacy/stan/nats-streaming-concepts/store-interface.md
  nats-concepts/pubsub: ./nats-concepts/core-nats/publish-subscribe/pubsub.md
  walkthrough/pubsub: ./nats-concepts/core-nats/publish-subscribe/pubsub_walkthrough.md
  compare-nats: ./nats-concepts/overview/compare-nats.md
  nats-concepts/intro: ./nats-concepts/overview/readme.md
  walkthrough/walkthrough_setup: ./nats-concepts/what-is-nats/walkthrough_setup.md
  faq: ./reference/faq.md
  nats-protocol/nats-protocol-demo: ./reference/nats-protocol/nats-protocol-demo.md
  whats_new_20: ./release_notes/whats_new_20.md
  whats_new_22: ./release_notes/whats_new_22.md
  
