name: CI

on:
  pull_request: {}

jobs:
  format_check:
    name: Format Check
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v3

      - name: Install packages
        run: npm ci

      - name: Verify formatting
        run: npm run format:check
